# Generated by Django 3.2.8 on 2021-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
        ('Simulation', '0002_alter_simulacoes_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simulacoes',
            new_name='Simulacao',
        ),
    ]
