# Generated by Django 3.2.8 on 2021-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_auto_20211118_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfis',
            name='peso_final',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfis',
            name='peso_inicial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perguntas',
            name='tipo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostas',
            name='sequencia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
