# Generated by Django 3.2.8 on 2021-11-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0003_auto_20211118_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntas',
            old_name='tipo',
            new_name='status',
        ),
    ]
