# Generated by Django 3.2.8 on 2021-11-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
        ('Polls', '0004_rename_tipo_perguntas_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motivos',
            new_name='Motivo',
        ),
    ]
