# Generated by Django 3.2.8 on 2021-11-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacoes',
            name='descricao',
            field=models.CharField(help_text='Informe a descrição da simulação', max_length=300, null=True),
        ),
    ]
