# Generated by Django 3.2.8 on 2021-11-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0011_simulacao_cenarios'),
        ('Simulation', '0004_auto_20211123_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao_acao',
            name='simulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.simulacao_cenarios'),
        ),
    ]
