# Generated by Django 3.2.8 on 2022-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0006_auto_20220223_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao_acao',
            name='classificacao_ia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
