# Generated by Django 3.2.8 on 2022-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0007_simulacao_acao_classificacao_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao_acao',
            name='valor_movimentacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
