# Generated by Django 3.2.8 on 2022-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0009_auto_20220323_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao_acao',
            name='dividend_yeld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
