# Generated by Django 3.2.8 on 2021-11-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Informe o código da ação', max_length=10)),
                ('nome', models.CharField(help_text='Informe o nome da ação', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grau_Instrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o grau de instrução', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do motivo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do perfil', max_length=100)),
                ('tipo', models.CharField(help_text='Informe o tipo de perfil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(help_text='Informe a pergunta', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da profissão', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(help_text='Informe a resposta', max_length=200)),
                ('pontuacao', models.DecimalField(decimal_places=4, max_digits=6)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.perguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('grau_instrucao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Polls.grau_instrucao')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Polls.perfis')),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Polls.profissoes')),
            ],
        ),
        migrations.CreateModel(
            name='Respostas_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField()),
                ('data_final', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Polls.respostas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Polls.usuarios')),
            ],
        ),
    ]
