# Generated by Django 3.2.8 on 2021-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
