# Generated by Django 3.2.8 on 2021-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0002_alter_simulacoes_descricao'),
        ('Portfolio', '0001_initial'),
        ('Polls', '0005_rename_motivos_motivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acoes',
            new_name='Acao',
        ),
        migrations.RenameModel(
            old_name='Perfis',
            new_name='Perfil',
        ),
        migrations.RenameModel(
            old_name='Perguntas',
            new_name='Pergunta',
        ),
        migrations.RenameModel(
            old_name='Profissoes',
            new_name='Profissao',
        ),
        migrations.RenameModel(
            old_name='Respostas',
            new_name='Resposta',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
