# Generated by Django 3.2.8 on 2021-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_auto_20211123_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], help_text='Gênero', max_length=1),
        ),
    ]
