# Generated by Django 3.2.8 on 2021-11-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulation', '0004_auto_20211123_1019'),
        ('Portfolio', '0003_alter_hist_alt_carteira_simulacao'),
        ('Polls', '0009_auto_20211123_1023'),
    ]
