# Generated by Django 3.2.8 on 2021-11-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_hist_alt_carteira_simulacao'),
        ('Simulation', '0005_alter_simulacao_acao_simulacao'),
        ('Polls', '0011_simulacao_cenarios'),
    ]
