# Generated by Django 3.2.8 on 2021-11-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0008_simulacao'),
        ('Polls', '0012_delete_simulacao_cenario'),
    ]

    operations = [
    ]
