# Generated by Django 3.2.8 on 2022-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0014_auto_20211129_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'Ação',
                     'verbose_name_plural': '5. Ações'},
        ),
        migrations.AlterModelOptions(
            name='grau_instrucao',
            options={'verbose_name': 'Grau de Instrução',
                     'verbose_name_plural': '2. Graus de Instrução'},
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={'verbose_name': 'Motivo',
                     'verbose_name_plural': '4. Motivos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil',
                     'verbose_name_plural': '1. Perfis'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name': 'Pergunta',
                     'verbose_name_plural': '6. Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissão',
                     'verbose_name_plural': '3. Profissões'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name': 'Resposta',
                     'verbose_name_plural': '7. Respostas'},
        ),
        migrations.AlterModelOptions(
            name='respostas_usuario',
            options={'verbose_name': 'Resposta do Usuário',
                     'verbose_name_plural': '99. Respostas dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='simulacao_cenarios',
            options={'verbose_name': 'Simulação',
                     'verbose_name_plural': '9. Simulações'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário',
                     'verbose_name_plural': '8. Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[(
                'm', 'Masculino'), ('f', 'Feminino')], help_text='Gênero', max_length=1),
        ),
    ]
