# Generated by Django 3.2.8 on 2022-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0015_auto_20220223_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='classificacao_ia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
