# Generated by Django 3.2.8 on 2022-03-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0016_auto_20220317_0805'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='acao',
            name='classificacao_ia',
        ),
    ]
