# Generated by Django 3.2.8 on 2022-03-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0017_auto_20220323_0650'),
    ]

    operations = [

    ]
