# Generated by Django 3.2.8 on 2022-03-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0018_delete_simulacao'),
    ]

    operations = [
    ]
