# Generated by Django 3.2.8 on 2022-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0021_auto_20220406_0719'),
    ]

    operations = [

        migrations.AddField(
            model_name='acao',
            name='split',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
