# Generated by Django 3.2.8 on 2021-11-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0008_simulacao'),
        ('Portfolio', '0002_alter_hist_alt_carteira_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_alt_carteira',
            name='simulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.simulacao'),
        ),
    ]
