# Generated by Django 3.2.8 on 2021-11-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0011_simulacao_cenarios'),
        ('Portfolio', '0003_alter_hist_alt_carteira_simulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_alt_carteira',
            name='simulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.simulacao_cenarios'),
        ),
    ]
