# Generated by Django 3.2.8 on 2022-02-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_hist_alt_carteira_simulacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carteiras',
            options={'verbose_name': 'Carteira', 'verbose_name_plural': 'Carteiras'},
        ),
        migrations.AlterModelOptions(
            name='hist_alt_carteira',
            options={'verbose_name': 'Histórico Carteira', 'verbose_name_plural': 'Histórico Carteiras'},
        ),
    ]
